# PostgresSQL properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:8000/virt_health
db.username=postgres
db.password=KiraWi

# Hibernate properties
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

